### ISSUE TITLE
预加载COOKIE值时出现错误

### ISSUE THREAD

**Issue by 18570353711** [Gerapy/GerapyPyppeteer#11]
SYSTEM:  Win10
SOFT: PyCharm
PYTHON : 3.7.7

### PIP LIST
(venv) D:\DEV\twitter\test_pyppeteer>pip list
Package          Version
appdirs          1.4.4
attrs            19.3.0
Automat          20.2.0
cffi             1.14.1
configparser     5.0.0
constantly       15.1.0
cryptography     3.0
cssselect        1.1.0
gerapy-pyppeteer 0.0.10
hyperlink        19.0.0
idna             2.10
incremental      17.5.0
itemadapter      0.1.0
lxml             4.5.2
mysql-connector  2.2.9
parsel           1.6.0
pip              19.0.3
Protego          0.1.16
pyasn1           0.4.8
pyasn1-modules   0.2.8
pycparser        2.20
PyDispatcher     2.0.5
pyee             7.0.2
PyHamcrest       2.0.2
pymongo          3.10.1
PyMySQL          0.10.0
pyOpenSSL        19.1.0
pyppeteer        0.2.2
python-dateutil  2.8.1
queuelib         1.5.0
Scrapy           2.2.1
service-identity 18.1.0
setuptools       40.8.0
six              1.15.0
tqdm             4.48.0
Twisted          20.3.0
urllib3          1.25.10
w3lib            1.22.0
websockets       8.1
zope.interface   5.1.0

### CODE
```
import scrapy
from gerapy_pyppeteer import PyppeteerRequest

class TwitterSpider(scrapy.Spider):
    name = 'twitter'
    allowed_domains = ['twitter.com']
    start_urls = ['https://twitter.com/etc_core',]
    cookies = 'xb=743834; __ssid=0e2ba81f68fbffb2472b476c0a8f92c; __gads=ID=a5ed52a55d917c7d:T=1595141059:S=ALNI_MZeHkYChINDZXXmBTqKqicALt-lwA; vp=948%2C1297%2C1.5%2C17%2Csearch-photos-everyone-view%3A2048; _sp_ses.df80=*; _sp_id.df80=a3764be4-d0d8-4d1e-9950-86623b3e907d.1596424125.1.1596424125.1596424125.369d4734-a85e-4f45-9f78-e3058f257ca6; AMCVS_48E815355BFE96970A495CD0%40AdobeOrg=1; AMCV_48E815355BFE96970A495CD0%40AdobeOrg=281789898%7CMCMID%7C50219748405086909233532121226234319542%7CMCAAMLH-1597028925%7C11%7CMCAAMB-1597028925%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1596431325s%7CNONE%7CvVersion%7C4.1.0'

    def start_requests(self):
        # 接装cookies
        cookie = {}
        for line in self.cookies.split(';'):
            key, value = line.split('=', 1)
            cookie[key] = value
        # 开始抓取用户UID
        for url in self.start_urls:
            yield PyppeteerRequest(url, callback=self.parse, meta={'proxy': "http://127.0.0.1:10800"}, cookies=cookie)

    def parse(self, response):
        print(response.status)
```

### OUTPUT
```
(venv) D:\DEV\twitter\test_pyppeteer>scrapy crawl twitter
2020-08-03 11:12:18 [scrapy.utils.log] INFO: Scrapy 2.2.1 started (bot: test_pyppeteer)
2020-08-03 11:12:18 [scrapy.utils.log] INFO: Versions: lxml 4.5.2.0, libxml2 2.9.5, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.
3.0, Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020
), cryptography 3.0, Platform Windows-10-10.0.18362-SP0
2020-08-03 11:12:18 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2020-08-03 11:12:18 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'test_pyppeteer',
 'CONCURRENT_REQUESTS': 1,
 'NEWSPIDER_MODULE': 'test_pyppeteer.spiders',
 'SPIDER_MODULES': ['test_pyppeteer.spiders']}
2020-08-03 11:12:18 [scrapy.extensions.telnet] INFO: Telnet Password: e1afc7df128ed74e
2020-08-03 11:12:18 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-08-03 11:12:19 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'gerapy_pyppeteer.downloadermiddlewares.PyppeteerMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-08-03 11:12:19 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-08-03 11:12:19 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-08-03 11:12:19 [scrapy.core.engine] INFO: Spider opened
2020-08-03 11:12:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-08-03 11:12:19 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-08-03 11:12:19 [gerapy.pyppeteer] DEBUG: processing request <GET https://twitter.com/etc_core>
2020-08-03 11:12:19 [gerapy.pyppeteer] DEBUG: pyppeteer_meta {'wait_until': 'domcontentloaded', 'wait_for': None, 'script': None, 'sleep': N
one, 'proxy': None, 'pretend': None, 'timeout': None, 'screenshot': None, 'ignore_resource_types': None}
2020-08-03 11:12:19 [gerapy.pyppeteer] DEBUG: set options {'headless': True, 'dumpio': False, 'devtools': False, 'args': ['--window-size=140
0,700', '--disable-extensions', '--hide-scrollbars', '--mute-audio', '--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu', '--proxy-s
erver=http://127.0.0.1:10800'], 'ignoreDefaultArgs': ['--enable-automation'], 'handleSIGINT': True, 'handleSIGTERM': True, 'handleSIGHUP': T
rue, 'autoClose': True}
[W:pyppeteer.page] False
[W:pyppeteer.page] about:blank
2020-08-03 11:12:19 [scrapy.core.scraper] ERROR: Error downloading <GET https://twitter.com/etc_core>
Traceback (most recent call last):
  File "d:\dev\twitter\venv\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\dev\twitter\venv\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "d:\dev\twitter\venv\lib\site-packages\scrapy\core\downloader\middleware.py", line 36, in process_request
    response = yield deferred_from_coro(method(request=request, spider=spider))
  File "d:\dev\twitter\venv\lib\site-packages\twisted\internet\defer.py", line 824, in adapt
    extracted = result.result()
  File "d:\dev\twitter\venv\lib\site-packages\gerapy_pyppeteer\downloadermiddlewares.py", line 204, in _process_request
    for k, v in request.cookies.items()
  File "d:\dev\twitter\venv\lib\site-packages\pyppeteer\page.py", line 547, in setCookie
    await self.deleteCookie(*items)
  File "d:\dev\twitter\venv\lib\site-packages\pyppeteer\page.py", line 514, in deleteCookie
    await self._client.send('Network.deleteCookies', item)
pyppeteer.errors.NetworkError: Protocol error (Network.deleteCookies): At least one of the url and domain needs to be specified
2020-08-03 11:12:19 [scrapy.core.engine] INFO: Closing spider (finished)
2020-08-03 11:12:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/pyppeteer.errors.NetworkError': 1,
 'elapsed_time_seconds': 0.825066,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 8, 3, 3, 12, 19, 845512),
 'log_count/DEBUG': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2020, 8, 3, 3, 12, 19, 20446)}
2020-08-03 11:12:19 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by Germey** [comment]
Fixed  in v0.0.11.

Please have a try:

```
pip3 install -U gerapy-pyppeteer 
```
