### ISSUE TITLE
everyone, does it work on linux without browser broken?

### ISSUE THREAD

**Issue by xkungfu** [Gerapy/GerapyPyppeteer#20]
**pyppeteer.errors: Browser closed unexpectedly** on ubuntu 20.04, python 3.8.5,

it seems that some options in GerapyPyppeteer caused the error,
or chromium version error,

I changed chromium version from 588429 to 839947, the error gone and get correct response.
but the chromium version 588429  work smoothly on windows7.

can you tell me if change version is a proper solution on linux?
and what caused the browser "closed unexpectedly".

thanks!

```
2021-02-22 09:04:04 [gerapy.pyppeteer] DEBUG: pyppeteer_meta {'wait_until': 'domcontentloaded', 'wait_for': None, 'script': None, 'sleep': 2, 'proxy': None, 'pretend': None, 'timeout': None, 'screenshot': None, 'ignore_resource_types': None}

2021-02-22 09:04:04 [gerapy.pyppeteer] DEBUG: set options {'headless': True, 'dumpio': False, 'devtools': False, 'args': ['--window-size=1400,700', '--disable-extensions', '--hide-scrollbars', '--mute-audio', '--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu'], 'ignoreDefaultArgs': ['--enable-automation'], 'handleSIGINT': True, 'handleSIGTERM': True, 'handleSIGHUP': True, 'autoClose': True}

2021-02-22 09:04:34 [scrapy.core.scraper] ERROR: Error downloading <GET https://dynamic5.scrape.center/page/3>

Traceback (most recent call last):
  File "/home/ds/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/ds/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/ds/env/lib/python3.8/site-packages/scrapy/core/downloader/middleware.py", line 39, in process_request
    response = yield deferred_from_coro(method(request=request, spider=spider))
  File "/home/ds/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/home/ds/env/lib/python3.8/site-packages/gerapy_pyppeteer/downloadermiddlewares.py", line 197, in _process_request
    browser = await launch(options)
  File "/home/ds/env/lib/python3.8/site-packages/pyppeteer/launcher.py", line 308, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/ds/env/lib/python3.8/site-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/ds/env/lib/python3.8/site-packages/pyppeteer/launcher.py", line 226, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

```

**Comment by Germey** [comment]
It should be fixed in 0.1.2, related to `GERAPY_ENABLE_REQUEST_INTERCEPTION`, set it to False should be fixed. 0.1.2 I set it default to False.

**Comment by timewalkerF** [comment]
0.2.4 依然有这个问题，在ubuntu 环境下

**Comment by timewalkerF** [comment]
apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget   安装环境就好了
